# Use the official Python 3.11 image from Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any required packages (if you have a requirements.txt)
# RUN pip install --no-cache-dir -r requirements.txt

# Command to run the Python script (change this to the specific day you want to run)
CMD ["python", "day2/solution.py"]
